#Example configuration options that can be placed in your main SiriProxy config.yml

##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################

    - name: 'Dreambox'
      git: 'git://github.com/ninja98/SiriProxy-Dreambox-Enigma2-Plugin.git' # git works just like specifying in Gemfile
      alias_file: "<full_path>/dreambox-aliases.yml"
      ip_dreambox: "<ip dreambox>"
      bouquet: "<name of bouquet to load>"
      twitter_consumer_key: "YOUR_KEY" 
      twitter_consumer_secret: "YOUR_SECRET"
      twitter_oauth_token: "YOUR_TOKEN" 
      twitter_oauth_token_secret: "YOUR_TOKEN_SECRET"
